namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_CONTENTSTACK_API_KEY: string;
      NEXT_PUBLIC_CONTENTSTACK_DELIVERY_TOKEN: string;
      NEXT_PUBLIC_CONTENTSTACK_ENVIRONMENT: string;
      NEXT_PUBLIC_CONTENTSTACK_PREVIEW_TOKEN: string;
      NEXT_PUBLIC_CONTENTSTACK_PREVIEW_HOST: string;
    }
  }